# Generated by Django 5.2.5 on 2025-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título (para controlo interno)')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo (opcional)')),
                ('image', models.ImageField(help_text='Dimensão recomendada: 1920x450 pixels.', upload_to='banners/', verbose_name='Imagem do Banner')),
                ('link_url', models.URLField(blank=True, max_length=255, verbose_name='URL de Destino (opcional)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Banner da Página Inicial',
                'verbose_name_plural': 'Banners da Página Inicial',
                'ordering': ['order'],
            },
        ),
    ]
