# Generated by Django 5.2.5 on 2025-08-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título do Banner')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo do Banner')),
                ('image', models.ImageField(help_text='Dimensão recomendada: 1920x350 pixels', upload_to='banners/')),
                ('link_url', models.URLField(blank=True, max_length=255, verbose_name='URL do Link')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners da Página Inicial',
                'ordering': ['order'],
            },
        ),
    ]
