# Generated by Django 5.2.5 on 2025-08-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Dimensão recomendada: 1920x350 pixels', upload_to='banners/'),
        ),
    ]
