# Generated by Django 5.2.5 on 2025-08-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título (para controlo interno)')),
                ('image', models.ImageField(upload_to='promotions/', verbose_name='Imagem do Card')),
                ('link_url', models.URLField(max_length=255, verbose_name='URL de Destino')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Card de Promoção',
                'verbose_name_plural': 'Cards de Promoção',
                'ordering': ['order'],
            },
        ),
    ]
