# Generated by Django 5.2.5 on 2025-08-11 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('CONTACTED', 'Contactado'), ('CONVERTED', 'Convertido em Venda'), ('LOST', 'Perdido')], default='NEW', max_length=20, verbose_name='Status da Solicitação')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('travel_date', models.DateField(blank=True, null=True, verbose_name='Data de Viagem Pretendida')),
                ('number_of_people', models.PositiveIntegerField(default=1, verbose_name='Número de Pessoas')),
                ('observations', models.TextField(blank=True, verbose_name='Observações do Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Cliente (se logado)')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer', verbose_name='Oferta de Interesse')),
            ],
            options={
                'verbose_name': 'Solicitação de Reserva',
                'verbose_name_plural': 'Solicitações de Reserva',
                'ordering': ['-created_at'],
            },
        ),
    ]
