# Generated by Django 5.2.5 on 2025-08-18 13:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título do Benefício')),
                ('description', models.TextField(verbose_name='Descrição Curta')),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Use este campo para um texto mais detalhado com formatação, imagens e links.', verbose_name='Descrição Longa (Opcional)')),
                ('icon_class', models.CharField(blank=True, help_text='Ex: fa-solid fa-user-doctor', max_length=50, verbose_name='Classe do Ícone (Font Awesome)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Benefício do Seguro Viagem',
                'verbose_name_plural': 'Benefícios do Seguro Viagem',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('answer', models.TextField(verbose_name='Resposta')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pergunta Frequente (Seguro)',
                'verbose_name_plural': 'Perguntas Frequentes (Seguro)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('price_info', models.CharField(blank=True, help_text='Ex: A partir de R$ 29,90/dia', max_length=50, verbose_name='Informação de Preço')),
                ('features', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Características (uma por linha)')),
                ('is_popular', models.BooleanField(default=False, verbose_name='É o plano mais popular?')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plano de Seguro Viagem',
                'verbose_name_plural': 'Planos de Seguro Viagem',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrustSeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Selo/Parceiro')),
                ('logo', models.ImageField(upload_to='seals/', verbose_name='Logo')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Selo de Confiança / Parceiro',
                'verbose_name_plural': 'Selos de Confiança / Parceiros',
                'ordering': ['order'],
            },
        ),
    ]
