# Generated by Django 5.2.5 on 2025-08-15 11:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancebenefit',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Use este campo para um texto mais detalhado com formatação, imagens e links.', verbose_name='Descrição Longa (Opcional)'),
        ),
    ]
