# Generated by Django 5.2.5 on 2025-08-12 13:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Página')),
                ('slug', models.SlugField(help_text="O texto que aparecerá na URL. Ex: 'quem-somos'", unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo da Página')),
                ('seo_title', models.CharField(blank=True, max_length=60, verbose_name='Título para o Google')),
                ('seo_description', models.TextField(blank=True, max_length=160, verbose_name='Descrição para o Google')),
            ],
            options={
                'verbose_name': 'Página de Conteúdo',
                'verbose_name_plural': 'Páginas de Conteúdo',
            },
        ),
    ]
