# Generated by Django 5.2.5 on 2025-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Página')),
                ('slug', models.SlugField(help_text='Usado na URL da página (ex: quem-somos)', unique=True)),
                ('content', models.TextField(blank=True, verbose_name='Conteúdo da Página')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Página de Conteúdo',
                'verbose_name_plural': 'Páginas de Conteúdo',
                'ordering': ['title'],
            },
        ),
    ]
