# Generated by Django 5.2.5 on 2025-08-12 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'Página de Conteúdo', 'verbose_name_plural': 'Páginas de Conteúdo'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_title',
        ),
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, verbose_name='Conteúdo da Página'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='Usado na URL da página (ex: quem-somos)', unique=True),
        ),
    ]
