# Generated by Django 5.2.5 on 2025-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('slug', models.SlugField(unique=True)),
                ('icon_class', models.CharField(blank=True, max_length=100, verbose_name='Classe do Ícone')),
                ('form_fields', models.JSONField(blank=True, help_text='Defina os campos para o formulário de busca deste serviço.', null=True, verbose_name='Campos do Formulário de Busca (JSON)')),
                ('section_headline', models.CharField(blank=True, help_text="Ex: 'Ofertas Incríveis de Hospedagem'", max_length=255, verbose_name='Título da Seção de Ofertas na Home')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['order'],
            },
        ),
    ]
