# Generated by Django 5.2.5 on 2025-08-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='form_fields',
            field=models.JSONField(blank=True, help_text='Defina os campos para o formulário de busca deste serviço.', null=True, verbose_name='Campos do Formulário de Busca (JSON)'),
        ),
        migrations.AddField(
            model_name='service',
            name='section_headline',
            field=models.CharField(blank=True, help_text="Ex: 'Ofertas Incríveis de Hospedagem'", max_length=255, verbose_name='Título da Seção de Ofertas na Home'),
        ),
    ]
