# Generated by Django 5.2.5 on 2025-08-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_form_fields_service_section_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
