# Generated by Django 5.2.5 on 2025-08-11 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(max_length=20, unique=True, verbose_name='Código da Reserva')),
                ('status', models.CharField(choices=[('AWAITING_CONTACT', 'Aguardando Contato'), ('CONTACTED', 'Contactado'), ('PENDING_PAYMENT', 'Aguardando Pagamento'), ('CONFIRMED', 'Confirmada'), ('CANCELED', 'Cancelada'), ('COMPLETED', 'Concluída')], default='AWAITING_CONTACT', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de Início da Viagem')),
                ('end_date', models.DateField(verbose_name='Data de Fim da Viagem')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total (R$)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações Internas (só para o admin)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='offers.offer', verbose_name='Oferta Associada (Opcional)')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReservationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição do Documento (ex: Voucher, Comprovante)')),
                ('file', models.FileField(upload_to='reservation_documents/', verbose_name='Arquivo')),
                ('uploaded_by', models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Cliente')], default='ADMIN', max_length=10, verbose_name='Enviado por')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reservations.reservation', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Documento da Reserva',
                'verbose_name_plural': 'Documentos da Reserva',
            },
        ),
    ]
