# Generated by Django 5.2.5 on 2025-08-10 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_image'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(verbose_name='Data de Fim da Viagem'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='offers.offer', verbose_name='Oferta Associada (Opcional)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(verbose_name='Data de Início da Viagem'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total (R$)'),
        ),
        migrations.AlterField(
            model_name='reservationdocument',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição do Documento (ex: Voucher, Bilhete Aéreo)'),
        ),
    ]
