# Generated by Django 5.2.5 on 2025-08-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_end_date_alter_reservation_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdocument',
            name='uploaded_by',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Cliente')], default='ADMIN', max_length=10, verbose_name='Enviado por'),
        ),
        migrations.AlterField(
            model_name='reservationdocument',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição do Documento (ex: Voucher, Comprovante)'),
        ),
    ]
