# Generated by Django 5.2.5 on 2025-08-13 12:59

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Anúncio (para controlo interno)')),
                ('image', models.ImageField(upload_to='blog_ads/', verbose_name='Imagem do Banner')),
                ('link_url', models.URLField(max_length=255, verbose_name='URL de Destino')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Banner de Publicidade (Blog)',
                'verbose_name_plural': 'Banners de Publicidade (Blog)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(help_text='Versão do nome para a URL, sem espaços ou acentos.', unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Tag')),
                ('slug', models.SlugField(help_text='Versão do nome para a URL, sem espaços ou acentos.', unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Post')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('featured_image', models.ImageField(help_text='Dimensão recomendada: 1200x600 pixels.', upload_to='blog_featured/', verbose_name='Imagem Destacada')),
                ('summary', models.TextField(max_length=200, verbose_name='Resumo (até 200 caracteres)')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo do Post')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fixar no Topo?')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Categoria')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
    ]
