# Generated by Django 5.2.5 on 2025-08-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código da Oferta')),
                ('title', models.CharField(max_length=255, verbose_name='Título Principal (Ex: Pacotes para Salvador)')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtítulo (Ex: Férias no Nordeste com Estilo)')),
                ('destination_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade de Destino')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='Imagem do Card')),
                ('details', models.TextField(blank=True, verbose_name='Detalhes Inclusos (um por linha)')),
                ('long_description', models.TextField(blank=True, verbose_name='Descrição Completa')),
                ('hotel_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Hotel (Opcional)')),
                ('hotel_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Avaliação do Hotel (Ex: 8.5)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Final')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início da Oferta')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Fim da Oferta')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Original')),
                ('price_per_person', models.BooleanField(default=True, verbose_name='É preço por pessoa?')),
                ('taxes_included', models.BooleanField(default=True, verbose_name='Taxas inclusas?')),
                ('origin', models.CharField(blank=True, max_length=100, verbose_name='Origem (ex: Saindo de São Paulo)')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (Dias)')),
                ('duration_nights', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (Noites)')),
                ('promo_tag', models.CharField(blank=True, max_length=50, verbose_name='Tag Promocional')),
                ('highlight_button', models.BooleanField(default=False, verbose_name="Destacar Botão 'Reservar'?")),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('show_on_landing_page', models.BooleanField(default=False, verbose_name='Mostrar na Página Inicial?')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
    ]
