# Generated by Django 5.2.5 on 2025-08-10 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título Principal')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtítulo')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('show_on_landing_page', models.BooleanField(default=False, verbose_name='Mostrar na Página Inicial?')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
    ]
