# Generated by Django 5.2.5 on 2025-08-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.TextField(blank=True, verbose_name='Detalhes (um por linha)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (Dias)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='duration_nights',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (Noites)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='highlight_button',
            field=models.BooleanField(default=False, verbose_name="Destacar Botão 'Reservar'?"),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='Imagem do Card'),
        ),
        migrations.AddField(
            model_name='offer',
            name='origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Origem (ex: Saindo de São Paulo)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Original (para mostrar desconto)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Final'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_per_person',
            field=models.BooleanField(default=True, verbose_name='É preço por pessoa?'),
        ),
        migrations.AddField(
            model_name='offer',
            name='promo_tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tag Promocional (ex: 30% OFF)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='taxes_included',
            field=models.BooleanField(default=True, verbose_name='Taxas inclusas?'),
        ),
    ]
