# Generated by Django 5.2.5 on 2025-08-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='destination_city',
            field=models.CharField(blank=True, help_text='Essencial para a busca. Ex: Salvador, Rio de Janeiro', max_length=100, verbose_name='Cidade de Destino'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='hotel_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Avaliação do Hotel (Ex: 8.5)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Descrição Completa'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Original'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='promo_tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tag Promocional'),
        ),
    ]
