# Generated by Django 5.2.5 on 2025-08-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_details_offer_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, help_text='Dimensão recomendada: 400x300 pixels', null=True, upload_to='offers/', verbose_name='Imagem do Card'),
        ),
    ]
