# Generated by Django 5.2.5 on 2025-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Hotel (Opcional)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='hotel_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Use um número de 0.0 a 10.0', max_digits=2, null=True, verbose_name='Avaliação do Hotel (Ex: 8.5)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='details',
            field=models.TextField(blank=True, verbose_name='Detalhes Inclusos (um por linha)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Original (para mostrar economia)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='promo_tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tag Promocional (ex: Oferta Imbatível)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='Subtítulo (Ex: Férias no Nordeste com Estilo)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título Principal (Ex: Pacotes para Salvador)'),
        ),
    ]
