# Generated by Django 5.2.5 on 2025-08-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offer_hotel_name_offer_hotel_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Descrição Completa (para a página de detalhes)'),
        ),
    ]
