# Generated by Django 5.2.5 on 2025-08-18 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Avaliação')),
                ('content', models.TextField(verbose_name='Conteúdo da Avaliação')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Nota (de 1 a 5)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='review_photos/', verbose_name='Foto da Viagem')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovada?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor da Avaliação')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='offers.offer', verbose_name='Oferta Avaliada (Opcional)')),
            ],
            options={
                'verbose_name': 'Avaliação de Cliente',
                'verbose_name_plural': 'Avaliações de Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
