# Generated by Django 5.2.5 on 2025-08-13 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0002_offer_destination_city_alter_offer_hotel_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Avaliação')),
                ('content', models.TextField(verbose_name='Conteúdo da Avaliação')),
                ('rating', models.IntegerField(choices=[(1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], verbose_name='Nota (Estrelas)')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Aprovada?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacar na Página Inicial?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor (Cliente)')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer', verbose_name='Oferta Avaliada')),
            ],
            options={
                'verbose_name': 'Avaliação de Cliente',
                'verbose_name_plural': 'Avaliações de Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
