# Generated by Django 5.2.5 on 2025-08-13 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_destination_city_alter_offer_hotel_rating_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, help_text='Uma foto enviada pelo cliente para ilustrar a experiência.', null=True, upload_to='review_photos/', verbose_name='Foto da Viagem (Opcional)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer', verbose_name='Oferta Avaliada (Opcional)'),
        ),
    ]
