# Generated by Django 5.2.5 on 2025-08-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_photo_alter_review_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/', verbose_name='Foto da Viagem'),
        ),
    ]
