# Generated by Django 5.2.5 on 2025-08-18 13:54

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título da Categoria')),
                ('slug', models.SlugField(help_text='Versão do título para a URL (ex: faturamento-e-reembolso)', unique=True)),
                ('icon_class', models.CharField(blank=True, help_text='Ex: fa-solid fa-file-invoice-dollar', max_length=50, verbose_name='Classe do Ícone (Font Awesome)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria de Ajuda',
                'verbose_name_plural': 'Categorias de Ajuda',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Resposta')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='help_center.helpcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Artigo de Ajuda',
                'verbose_name_plural': 'Artigos de Ajuda',
                'ordering': ['order'],
            },
        ),
    ]
