# Generated by Django 5.2.5 on 2025-08-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(blank=True, help_text='Deixe em branco para gerar automaticamente a partir do nome.', max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Use para definir a ordem de exibição das categorias (0 primeiro).')),
            ],
            options={
                'verbose_name': 'Categoria de Ajuda',
                'verbose_name_plural': 'Categorias de Ajuda',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Artigo / Pergunta')),
                ('slug', models.SlugField(blank=True, help_text='Deixe em branco para gerar automaticamente a partir do título.', max_length=220, unique=True)),
                ('content', models.TextField(verbose_name='Conteúdo / Resposta')),
                ('order', models.PositiveIntegerField(default=0, help_text='Use para definir a ordem de exibição dos artigos dentro de uma categoria.')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='help_center.helpcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Artigo de Ajuda',
                'verbose_name_plural': 'Artigos de Ajuda',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
