# Generated by Django 5.2.5 on 2025-08-14 15:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helparticle',
            options={'ordering': ['order'], 'verbose_name': 'Artigo de Ajuda', 'verbose_name_plural': 'Artigos de Ajuda'},
        ),
        migrations.AlterModelOptions(
            name='helpcategory',
            options={'ordering': ['order'], 'verbose_name': 'Categoria de Ajuda', 'verbose_name_plural': 'Categorias de Ajuda'},
        ),
        migrations.RemoveField(
            model_name='helparticle',
            name='content',
        ),
        migrations.RemoveField(
            model_name='helparticle',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='helparticle',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='helparticle',
            name='title',
        ),
        migrations.RemoveField(
            model_name='helpcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='helparticle',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Resposta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helparticle',
            name='question',
            field=models.CharField(default='', max_length=255, verbose_name='Pergunta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpcategory',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Ex: fa-solid fa-file-invoice-dollar', max_length=50, verbose_name='Classe do Ícone (Font Awesome)'),
        ),
        migrations.AddField(
            model_name='helpcategory',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Título da Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='helpcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='helpcategory',
            name='slug',
            field=models.SlugField(help_text='Versão do título para a URL (ex: faturamento-e-reembolso)', unique=True),
        ),
    ]
