# Generated by Django 5.2.5 on 2025-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Membro')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('photo', models.ImageField(help_text='Dimensão recomendada: 400x400 pixels (quadrada)', upload_to='team/')),
                ('bio', models.CharField(blank=True, max_length=255, verbose_name='Mini Frase de Apresentação')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Membro da Equipa',
                'verbose_name_plural': 'Equipa',
                'ordering': ['order'],
            },
        ),
    ]
