# Generated by Django 5.2.5 on 2025-08-11 17:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Agência de Viagens', max_length=255, verbose_name='Nome do Site')),
                ('logo', models.ImageField(blank=True, help_text='Dimensão recomendada: 250x80 pixels', null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Ícone quadrado. Dimensão recomendada: 64x64 pixels.', null=True, upload_to='favicons/', verbose_name='Favicon do Site')),
                ('logo_height', models.PositiveIntegerField(default=50, help_text='Altura do logo em pixels (ex: 50).', verbose_name='Altura do Logo (em pixels)')),
                ('hero_background_color', colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Busca')),
                ('hero_background_image', models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x500 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Busca')),
                ('newsletter_headline', models.CharField(blank=True, max_length=100, verbose_name='Título da Newsletter')),
                ('newsletter_subheadline', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo da Newsletter')),
                ('newsletter_button_text', models.CharField(default='Inscrever-se', max_length=50, verbose_name='Texto do Botão da Newsletter')),
                ('newsletter_background_color', colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Newsletter')),
                ('newsletter_background_image', models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x400 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Newsletter')),
                ('banner_autoplay_speed', models.PositiveIntegerField(default=5000, help_text='Velocidade em milissegundos (ex: 5000 para 5 segundos). Digite 0 para desativar.', verbose_name='Velocidade do Carrossel de Banners (ms)')),
                ('offer_carousel_speed', models.PositiveIntegerField(default=0, help_text='Velocidade em milissegundos (ex: 4000 para 4 segundos). Digite 0 para desativar.', verbose_name='Velocidade do Carrossel de Ofertas (ms)')),
                ('main_font', models.CharField(default='Poppins', max_length=100, verbose_name='Fonte Principal')),
                ('primary_color', colorfield.fields.ColorField(default='#0d6efd', image_field=None, max_length=25, samples=None, verbose_name='Cor Primária (Botões e Links)')),
                ('top_bar_bg_color', colorfield.fields.ColorField(default='#F8F9FA', image_field=None, max_length=25, samples=None, verbose_name='Fundo da Barra Superior')),
                ('top_bar_text_color', colorfield.fields.ColorField(default='#6C757D', image_field=None, max_length=25, samples=None, verbose_name='Texto da Barra Superior')),
                ('main_header_bg_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Fundo do Cabeçalho Principal')),
                ('main_header_text_color', colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Texto do Cabeçalho Principal')),
                ('footer_bg_color', colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Fundo do Rodapé')),
                ('footer_text_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Texto do Rodapé')),
                ('footer_text', models.TextField(blank=True, verbose_name='Texto do Rodapé')),
                ('seo_title', models.CharField(blank=True, max_length=60, verbose_name='Título para o Google')),
                ('seo_description', models.TextField(blank=True, max_length=160, verbose_name='Descrição para o Google')),
                ('tracking_header_scripts', models.TextField(blank=True, verbose_name='Scripts no Cabeçalho (<head>)')),
                ('tracking_body_start_scripts', models.TextField(blank=True, verbose_name='Scripts no Início do Corpo (<body>)')),
                ('tracking_body_end_scripts', models.TextField(blank=True, verbose_name='Scripts no Fim do Corpo (</body>)')),
                ('offer_code_prefix', models.CharField(default='OFR', help_text='As 3 a 5 letras que irão no início de cada código de oferta (ex: OFR).', max_length=5, verbose_name='Prefixo do Código da Oferta')),
            ],
            options={
                'verbose_name': 'Configuração Geral do Site',
            },
        ),
    ]
