# Generated by Django 5.2.5 on 2025-08-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Agência de Viagens', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Dimensão recomendada: 250x80 pixels', null=True, upload_to='logos/')),
                ('primary_color', models.CharField(default='#0d6efd', help_text='Cor principal do site (formato hexadecimal, ex: #0d6efd)', max_length=7)),
                ('footer_text', models.TextField(blank=True, help_text='Texto que aparecerá no rodapé do site.')),
            ],
            options={
                'verbose_name': 'Configuração Geral do Site',
                'verbose_name_plural': 'Configurações Gerais do Site',
            },
        ),
    ]
