# Generated by Django 5.2.5 on 2025-08-18 10:42

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('televendas_phone', models.CharField(blank=True, help_text='Número principal para ligações diretas. Ex: (11) 4002-8922', max_length=20, verbose_name='Telefone de Televendas')),
                ('televendas_page_title', models.CharField(blank=True, default='Fale com nossa equipa de Televendas', max_length=100, verbose_name='Título da Página de Televendas')),
                ('televendas_page_subtitle', models.CharField(blank=True, default='Estamos prontos para o ajudar a reservar a sua viagem e a tirar todas as dúvidas.', max_length=255, verbose_name='Subtítulo da Página de Televendas')),
                ('televendas_benefits', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Use listas ou parágrafos para destacar os benefícios do seu atendimento.', verbose_name='Benefícios / Informações Extras')),
                ('site_name', models.CharField(default='Agência de Viagens', max_length=255, verbose_name='Nome do Site')),
                ('logo', models.ImageField(blank=True, help_text='Dimensão recomendada: 250x80 pixels', null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Ícone quadrado. Dimensão recomendada: 64x64 pixels.', null=True, upload_to='favicons/', verbose_name='Favicon do Site')),
                ('logo_height', models.PositiveIntegerField(default=50, help_text='Altura do logo em pixels (ex: 50).', verbose_name='Altura do Logo (em pixels)')),
                ('public_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail Público de Contato')),
                ('public_whatsapp', models.CharField(blank=True, help_text='Use o formato internacional, ex: 5511999999999', max_length=20, verbose_name='WhatsApp Público de Contato')),
                ('address_street', models.CharField(blank=True, max_length=255, verbose_name='Rua e Número')),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('address_cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('opening_hours', models.TextField(blank=True, help_text='Use uma linha para cada dia. Ex: Seg - Sex: 09:00 - 18:00', verbose_name='Horário de Funcionamento')),
                ('google_maps_embed_url', models.URLField(blank=True, max_length=500, verbose_name='URL de Incorporação do Google Maps')),
                ('contact_page_title', models.CharField(blank=True, default='Entre em Contato', max_length=100, verbose_name='Título da Página de Contato')),
                ('contact_page_subtitle', models.CharField(blank=True, default='Será um prazer atendê-lo!', max_length=255, verbose_name='Subtítulo da Página de Contato')),
                ('contact_form_subjects', models.TextField(blank=True, default='Dúvidas Gerais\nOrçamentos\nReclamações\nElogios', help_text='Digite um assunto por linha.', verbose_name='Assuntos do Formulário de Contato')),
                ('offer_code_prefix', models.CharField(default='OFR', max_length=5, verbose_name='Prefixo do Código da Oferta')),
                ('hero_background_color', colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Seção de Busca')),
                ('hero_background_image', models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x500 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Seção de Busca')),
                ('booking_form_bg_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo do Formulário de Busca')),
                ('newsletter_headline', models.CharField(blank=True, max_length=100, verbose_name='Título da Newsletter')),
                ('newsletter_subheadline', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo da Newsletter')),
                ('newsletter_button_text', models.CharField(default='Inscrever-se', max_length=50, verbose_name='Texto do Botão da Newsletter')),
                ('newsletter_background_color', colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Newsletter')),
                ('newsletter_background_image', models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x400 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Newsletter')),
                ('banner_autoplay_speed', models.PositiveIntegerField(default=5000, help_text='Velocidade em milissegundos (ex: 5000 para 5 segundos). Digite 0 para desativar.', verbose_name='Velocidade do Carrossel de Banners (ms)')),
                ('offer_carousel_speed', models.PositiveIntegerField(default=0, help_text='Velocidade em milissegundos (ex: 4000 para 4 segundos). Digite 0 para desativar.', verbose_name='Velocidade do Carrossel de Ofertas (ms)')),
                ('main_font', models.CharField(default='Poppins', max_length=100, verbose_name='Fonte Principal')),
                ('primary_color', colorfield.fields.ColorField(default='#0d6efd', image_field=None, max_length=25, samples=None, verbose_name='Cor Primária (Botões e Links)')),
                ('page_header_bg_color', colorfield.fields.ColorField(default='#003366', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo Padrão dos Cabeçalhos de Página')),
                ('top_bar_bg_color', colorfield.fields.ColorField(default='#F8F9FA', image_field=None, max_length=25, samples=None, verbose_name='Fundo da Barra Superior')),
                ('top_bar_text_color', colorfield.fields.ColorField(default='#6C757D', image_field=None, max_length=25, samples=None, verbose_name='Texto da Barra Superior')),
                ('main_header_bg_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Fundo do Cabeçalho Principal')),
                ('main_header_text_color', colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Texto do Cabeçalho Principal')),
                ('footer_bg_color', colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Fundo do Rodapé')),
                ('footer_text_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Texto do Rodapé')),
                ('footer_text', models.TextField(blank=True, verbose_name='Texto do Rodapé')),
                ('seo_title', models.CharField(blank=True, max_length=60, verbose_name='Título para o Google')),
                ('seo_description', models.TextField(blank=True, max_length=160, verbose_name='Descrição para o Google')),
                ('tracking_header_scripts', models.TextField(blank=True, verbose_name='Scripts no Cabeçalho (<head>)')),
                ('tracking_body_start_scripts', models.TextField(blank=True, verbose_name='Scripts no Início do Corpo (<body>)')),
                ('tracking_body_end_scripts', models.TextField(blank=True, verbose_name='Scripts no Fim do Corpo (</body>)')),
                ('about_us_header_image', models.ImageField(blank=True, help_text='Imagem de abertura da página. Dimensão recomendada: 1920x500 pixels.', null=True, upload_to='pages/', verbose_name='Imagem de Cabeçalho (Quem Somos)')),
                ('about_us_history', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='História da Agência')),
                ('about_us_mission', models.TextField(blank=True, verbose_name='Nossa Missão')),
                ('about_us_vision', models.TextField(blank=True, verbose_name='Nossa Visão')),
                ('about_us_values', models.TextField(blank=True, verbose_name='Nossos Valores (um por linha)')),
                ('stat_years', models.CharField(default='10+', max_length=10, verbose_name='Anos no Mercado')),
                ('stat_destinations', models.CharField(default='500+', max_length=10, verbose_name='Destinos Atendidos')),
                ('stat_clients', models.CharField(default='10.000+', max_length=10, verbose_name='Clientes Felizes')),
                ('experiences_page_title', models.CharField(blank=True, default='O que nossos viajantes dizem', max_length=100, verbose_name='Título da Página de Experiências')),
                ('experiences_page_subtitle', models.CharField(blank=True, default='Histórias reais que inspiram novas viagens.', max_length=255, verbose_name='Subtítulo da Página de Experiências')),
            ],
            options={
                'verbose_name': 'Configuração Geral do Site',
            },
        ),
    ]
