# Generated by Django 5.2.5 on 2025-08-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='banner_autoplay_speed',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_background_color',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_background_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='newsletter_background_color',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='newsletter_background_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='newsletter_button_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='newsletter_headline',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='newsletter_subheadline',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='offer_carousel_speed',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail Público de Contato'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='public_whatsapp',
            field=models.CharField(blank=True, help_text='Use o formato internacional, ex: 5511999999999', max_length=20, verbose_name='WhatsApp Público de Contato'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='offer_code_prefix',
            field=models.CharField(default='OFR', help_text='As 3 a 5 letras que irão no início de cada código de oferta (ex: RMV).', max_length=5, verbose_name='Prefixo do Código da Oferta'),
        ),
    ]
