# Generated by Django 5.2.5 on 2025-08-11 19:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_remove_siteconfiguration_banner_autoplay_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='banner_autoplay_speed',
            field=models.PositiveIntegerField(default=5000, help_text='Velocidade em milissegundos (ex: 5000 para 5 segundos). Digite 0 para desativar.', verbose_name='Velocidade do Carrossel de Banners (ms)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_background_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Busca'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x500 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Busca'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_background_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_background_image',
            field=models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x400 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_button_text',
            field=models.CharField(default='Inscrever-se', max_length=50, verbose_name='Texto do Botão da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_headline',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_subheadline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtítulo da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='offer_carousel_speed',
            field=models.PositiveIntegerField(default=0, help_text='Velocidade em milissegundos (ex: 4000 para 4 segundos). Digite 0 para desativar.', verbose_name='Velocidade do Carrossel de Ofertas (ms)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícone da aba do navegador. Use uma imagem quadrada (ex: 64x64 pixels).', null=True, upload_to='favicons/', verbose_name='Favicon do Site'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo_height',
            field=models.PositiveIntegerField(default=50, help_text='Altura do logo em pixels (ex: 50). A largura será ajustada automaticamente.', verbose_name='Altura do Logo (em pixels)'),
        ),
    ]
