# Generated by Django 5.2.5 on 2025-08-10 10:54

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_siteconfiguration_logo_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Configuração Geral do Site'},
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='logo_height',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_bg_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo do Rodapé'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Cor do Texto do Rodapé'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_font',
            field=models.CharField(default='Poppins', help_text='Nome da fonte principal do Google Fonts (ex: Poppins, Lato, Montserrat)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_header_bg_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo do Cabeçalho Principal'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_header_text_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Cor do Texto do Cabeçalho Principal'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='top_bar_bg_color',
            field=colorfield.fields.ColorField(default='#F8F9FA', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Barra Superior'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='top_bar_text_color',
            field=colorfield.fields.ColorField(default='#6C757D', image_field=None, max_length=25, samples=None, verbose_name='Cor do Texto da Barra Superior'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#0d6efd', help_text='Cor principal para botões e links', image_field=None, max_length=25, samples=None),
        ),
    ]
