# Generated by Django 5.2.5 on 2025-08-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_siteconfiguration_banner_autoplay_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço Físico'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_form_subjects',
            field=models.TextField(blank=True, default='Dúvidas Gerais\nOrçamentos\nReclamações\nElogios', help_text='Digite um assunto por linha. Eles aparecerão como opções para o cliente.', verbose_name='Assuntos do Formulário de Contato'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_page_subtitle',
            field=models.CharField(blank=True, default='Será um prazer atendê-lo!', max_length=255, verbose_name='Subtítulo da Página de Contato'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_page_title',
            field=models.CharField(blank=True, default='Entre em Contato', max_length=100, verbose_name='Título da Página de Contato'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, help_text="Vá ao Google Maps, pesquise o seu endereço, clique em 'Partilhar', depois em 'Incorporar um mapa' e copie o link que começa com 'https://www.google.com/maps/embed...'", max_length=500, verbose_name='URL de Incorporação do Google Maps'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='Horário de Funcionamento'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícone quadrado. Dimensão recomendada: 64x64 pixels.', null=True, upload_to='favicons/', verbose_name='Favicon do Site'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo_height',
            field=models.PositiveIntegerField(default=50, help_text='Altura do logo em pixels (ex: 50).', verbose_name='Altura do Logo (em pixels)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='offer_code_prefix',
            field=models.CharField(default='OFR', max_length=5, verbose_name='Prefixo do Código da Oferta'),
        ),
    ]
