# Generated by Django 5.2.5 on 2025-08-10 11:04

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_siteconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo_height',
            field=models.PositiveIntegerField(default=50, help_text='Altura do logo em pixels (ex: 50). A largura será ajustada automaticamente.', verbose_name='Altura do Logo (em pixels)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Texto que aparecerá no rodapé do site.', verbose_name='Texto do Rodapé'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='main_font',
            field=models.CharField(default='Poppins', help_text='Nome da fonte principal do Google Fonts (ex: Poppins, Lato, Montserrat)', max_length=100, verbose_name='Fonte Principal'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#0d6efd', image_field=None, max_length=25, samples=None, verbose_name='Cor Primária (Botões e Links)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='Agência de Viagens', max_length=255, verbose_name='Nome do Site'),
        ),
    ]
