# Generated by Django 5.2.5 on 2025-08-12 12:39

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_siteconfiguration_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='address_cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='address_neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='address_state',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rua e Número'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='booking_form_bg_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo do Formulário de Busca'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_form_subjects',
            field=models.TextField(blank=True, default='Dúvidas Gerais\nOrçamentos\nReclamações\nElogios', help_text='Digite um assunto por linha.', verbose_name='Assuntos do Formulário de Contato'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL de Incorporação do Google Maps'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_background_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Seção de Busca'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x500 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Seção de Busca'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Use uma linha para cada dia. Ex: Seg - Sex: 09:00 - 18:00', verbose_name='Horário de Funcionamento'),
        ),
    ]
