# Generated by Django 5.2.5 on 2025-08-10 12:44

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_siteconfiguration_favicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='footer_bg_color',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='footer_text_color',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='main_header_bg_color',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='main_header_text_color',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='top_bar_text_color',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='tracking_body_end_scripts',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='tracking_body_start_scripts',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='tracking_header_scripts',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_background_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Busca'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x500 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Busca'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_background_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_background_image',
            field=models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x400 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_button_text',
            field=models.CharField(default='Inscrever-se', max_length=50, verbose_name='Texto do Botão da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_headline',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_subheadline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtítulo da Newsletter'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícone quadrado. Dimensão recomendada: 64x64 pixels.', null=True, upload_to='favicons/', verbose_name='Favicon do Site'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo_height',
            field=models.PositiveIntegerField(default=50, help_text='Altura do logo em pixels (ex: 50).', verbose_name='Altura do Logo (em pixels)'),
        ),
    ]
