# Generated by Django 5.2.5 on 2025-08-10 12:55

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_remove_siteconfiguration_footer_bg_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_background_color',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_background_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='newsletter_background_color',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='newsletter_background_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='newsletter_button_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='newsletter_headline',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='newsletter_subheadline',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_bg_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo do Rodapé'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Cor do Texto do Rodapé'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_header_bg_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo do Cabeçalho Principal'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_header_text_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Cor do Texto do Cabeçalho Principal'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='seo_description',
            field=models.TextField(blank=True, help_text='O texto que aparece sob o título nos resultados do Google (máx. 160 caracteres).', max_length=160, verbose_name='Descrição para o Google'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='seo_title',
            field=models.CharField(blank=True, help_text='O título que aparece na aba do navegador e nos resultados do Google (máx. 60 caracteres).', max_length=60, verbose_name='Título para o Google'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='top_bar_text_color',
            field=colorfield.fields.ColorField(default='#6C757D', image_field=None, max_length=25, samples=None, verbose_name='Cor do Texto da Barra Superior'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tracking_body_end_scripts',
            field=models.TextField(blank=True, help_text='Cole aqui os scripts que devem ir antes de </body>.', verbose_name='Scripts no Fim do Corpo (</body>)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tracking_body_start_scripts',
            field=models.TextField(blank=True, help_text='Cole aqui os scripts que devem ir logo após a tag <body> (ex: Google Tag Manager).', verbose_name='Scripts no Início do Corpo (<body>)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tracking_header_scripts',
            field=models.TextField(blank=True, help_text='Cole aqui os scripts que devem ir antes de </head> (ex: Google Analytics, Pixel do Facebook).', verbose_name='Scripts no Cabeçalho (<head>)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícone da aba do navegador. Use uma imagem quadrada (ex: 64x64 pixels).', null=True, upload_to='favicons/', verbose_name='Favicon do Site'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Texto que aparecerá no rodapé do site.', verbose_name='Texto do Rodapé'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo_height',
            field=models.PositiveIntegerField(default=50, help_text='Altura do logo em pixels (ex: 50). A largura será ajustada automaticamente.', verbose_name='Altura do Logo (em pixels)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='main_font',
            field=models.CharField(default='Poppins', help_text='Nome da fonte principal do Google Fonts (ex: Poppins, Lato, Montserrat)', max_length=100, verbose_name='Fonte Principal'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='top_bar_bg_color',
            field=colorfield.fields.ColorField(default='#F8F9FA', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Barra Superior'),
        ),
    ]
