# Generated by Django 5.2.5 on 2025-08-12 13:52

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_remove_siteconfiguration_address_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_us_header_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_us_history',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_us_mission',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_us_values',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_us_vision',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='stat_clients',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='stat_destinations',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='stat_years',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='banner_autoplay_speed',
            field=models.PositiveIntegerField(default=5000, help_text='Velocidade em milissegundos (ex: 5000 para 5 segundos). Digite 0 para desativar.', verbose_name='Velocidade do Carrossel de Banners (ms)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícone da aba do navegador. Use uma imagem quadrada (ex: 64x64 pixels).', null=True, upload_to='favicons/', verbose_name='Favicon do Site'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_bg_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Fundo do Rodapé'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.TextField(blank=True, verbose_name='Texto do Rodapé'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Texto do Rodapé'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_background_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Busca'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x500 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Busca'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(blank=True, help_text='Dimensão recomendada: 250x80 pixels', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo_height',
            field=models.PositiveIntegerField(default=50, help_text='Altura do logo em pixels (ex: 50). A largura será ajustada automaticamente.', verbose_name='Altura do Logo (em pixels)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_font',
            field=models.CharField(default='Poppins', max_length=100, verbose_name='Fonte Principal'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_header_bg_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Fundo do Cabeçalho Principal'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_header_text_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Texto do Cabeçalho Principal'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_background_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_background_image',
            field=models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x400 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_button_text',
            field=models.CharField(default='Inscrever-se', max_length=50, verbose_name='Texto do Botão da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_headline',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_subheadline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtítulo da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='offer_carousel_speed',
            field=models.PositiveIntegerField(default=0, help_text='Velocidade em milissegundos (ex: 4000 para 4 segundos). Digite 0 para desativar.', verbose_name='Velocidade do Carrossel de Ofertas (ms)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='offer_code_prefix',
            field=models.CharField(default='OFR', help_text='As 3 a 5 letras que irão no início de cada código de oferta (ex: RMV).', max_length=5, verbose_name='Prefixo do Código da Oferta'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#0d6efd', image_field=None, max_length=25, samples=None, verbose_name='Cor Primária (Botões e Links)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail Público de Contato'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='public_whatsapp',
            field=models.CharField(blank=True, help_text='Use o formato internacional, ex: 5511999999999', max_length=20, verbose_name='WhatsApp Público de Contato'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='seo_description',
            field=models.TextField(blank=True, max_length=160, verbose_name='Descrição para o Google'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Título para o Google'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='Agência de Viagens', max_length=255, verbose_name='Nome do Site'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='top_bar_bg_color',
            field=colorfield.fields.ColorField(default='#F8F9FA', image_field=None, max_length=25, samples=None, verbose_name='Fundo da Barra Superior'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='top_bar_text_color',
            field=colorfield.fields.ColorField(default='#6C757D', image_field=None, max_length=25, samples=None, verbose_name='Texto da Barra Superior'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tracking_body_end_scripts',
            field=models.TextField(blank=True, verbose_name='Scripts no Fim do Corpo (</body>)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tracking_body_start_scripts',
            field=models.TextField(blank=True, verbose_name='Scripts no Início do Corpo (<body>)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tracking_header_scripts',
            field=models.TextField(blank=True, verbose_name='Scripts no Cabeçalho (<head>)'),
        ),
    ]
