# Generated by Django 5.2.5 on 2025-08-10 12:57

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_remove_siteconfiguration_hero_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_background_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Busca'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x500 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Busca'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_background_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_background_image',
            field=models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x400 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_button_text',
            field=models.CharField(default='Inscrever-se', max_length=50, verbose_name='Texto do Botão da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_headline',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_subheadline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtítulo da Newsletter'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_bg_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None, verbose_name='Fundo do Rodapé'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.TextField(blank=True, verbose_name='Texto do Rodapé'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Texto do Rodapé'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='main_font',
            field=models.CharField(default='Poppins', max_length=100, verbose_name='Fonte Principal'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='main_header_bg_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Fundo do Cabeçalho Principal'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='main_header_text_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Texto do Cabeçalho Principal'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='top_bar_bg_color',
            field=colorfield.fields.ColorField(default='#F8F9FA', image_field=None, max_length=25, samples=None, verbose_name='Fundo da Barra Superior'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='top_bar_text_color',
            field=colorfield.fields.ColorField(default='#6C757D', image_field=None, max_length=25, samples=None, verbose_name='Texto da Barra Superior'),
        ),
    ]
