# Generated by Django 5.2.5 on 2025-08-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_siteconfiguration_hero_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='banner_autoplay_speed',
            field=models.PositiveIntegerField(default=5000, help_text='Velocidade em milissegundos (ex: 5000 para 5 segundos). Digite 0 para desativar.', verbose_name='Velocidade do Carrossel de Banners (ms)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='offer_carousel_speed',
            field=models.PositiveIntegerField(default=0, help_text='Velocidade em milissegundos (ex: 4000 para 4 segundos). Digite 0 para desativar.', verbose_name='Velocidade do Carrossel de Ofertas (ms)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícone quadrado. Dimensão recomendada: 64x64 pixels.', null=True, upload_to='favicons/', verbose_name='Favicon do Site'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo_height',
            field=models.PositiveIntegerField(default=50, help_text='Altura do logo em pixels (ex: 50).', verbose_name='Altura do Logo (em pixels)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='seo_description',
            field=models.TextField(blank=True, max_length=160, verbose_name='Descrição para o Google'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Título para o Google'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='tracking_body_end_scripts',
            field=models.TextField(blank=True, verbose_name='Scripts no Fim do Corpo (</body>)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='tracking_body_start_scripts',
            field=models.TextField(blank=True, verbose_name='Scripts no Início do Corpo (<body>)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='tracking_header_scripts',
            field=models.TextField(blank=True, verbose_name='Scripts no Cabeçalho (<head>)'),
        ),
    ]
