# Generated by Django 5.2.5 on 2025-08-12 14:21

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_siteconfiguration_address_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address_cep',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address_neighborhood',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address_state',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='booking_form_bg_color',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='contact_form_subjects',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='contact_page_subtitle',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='contact_page_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='google_maps_embed_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='opening_hours',
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícone da aba do navegador. Use uma imagem quadrada (ex: 64x64 pixels).', null=True, upload_to='favicons/', verbose_name='Favicon do Site'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_background_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo da Busca'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Opcional. Dimensão recomendada: 1920x500 pixels.', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo da Busca'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo_height',
            field=models.PositiveIntegerField(default=50, help_text='Altura do logo em pixels (ex: 50). A largura será ajustada automaticamente.', verbose_name='Altura do Logo (em pixels)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='offer_code_prefix',
            field=models.CharField(default='OFR', help_text='As 3 a 5 letras que irão no início de cada código de oferta (ex: RMV).', max_length=5, verbose_name='Prefixo do Código da Oferta'),
        ),
    ]
