# Generated by Django 5.2.5 on 2025-08-13 15:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_siteconfiguration_about_us_header_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_header_bg_color',
            field=colorfield.fields.ColorField(default='#003366', image_field=None, max_length=25, samples=None, verbose_name='Cor de Fundo Padrão dos Cabeçalhos de Página'),
        ),
    ]
