# Generated by Django 5.2.5 on 2025-08-14 16:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0013_alter_siteconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='televendas_benefits',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Use listas ou parágrafos para destacar os benefícios do seu atendimento.', verbose_name='Benefícios / Informações Extras'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='televendas_page_subtitle',
            field=models.CharField(blank=True, default='Estamos prontos para o ajudar a reservar a sua viagem e a tirar todas as dúvidas.', max_length=255, verbose_name='Subtítulo da Página de Televendas'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='televendas_page_title',
            field=models.CharField(blank=True, default='Fale com nossa equipa de Televendas', max_length=100, verbose_name='Título da Página de Televendas'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='televendas_phone',
            field=models.CharField(blank=True, help_text='Número principal para ligações diretas. Ex: (11) 4002-8922', max_length=20, verbose_name='Telefone de Televendas'),
        ),
    ]
