# Generated by Django 5.2.5 on 2025-08-15 13:16

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0016_alter_siteconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_us_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_us_history',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_us_mission',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_us_values',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_us_vision',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='banner_autoplay_speed',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='booking_form_bg_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_form_subjects',
            field=models.TextField(blank=True, default='Dúvidas Gerais\nOrçamentos'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_page_subtitle',
            field=models.CharField(blank=True, default='Será um prazer atendê-lo!', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_page_title',
            field=models.CharField(blank=True, default='Entre em Contato', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='experiences_page_subtitle',
            field=models.CharField(blank=True, default='Histórias reais que inspiram novas viagens.', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='experiences_page_title',
            field=models.CharField(blank=True, default='O que nossos viajantes dizem', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='Favicon do Site'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_bg_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_background_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo_height',
            field=models.PositiveIntegerField(default=50, verbose_name='Altura do Logo (em pixels)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='main_font',
            field=models.CharField(default='Poppins', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='main_header_bg_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='main_header_text_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='newsletter_background_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='newsletter_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='newsletter_button_text',
            field=models.CharField(default='Inscrever-se', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='newsletter_headline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='newsletter_subheadline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='offer_carousel_speed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='offer_code_prefix',
            field=models.CharField(default='OFR', max_length=5),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='opening_hours',
            field=models.TextField(blank=True, verbose_name='Horário de Funcionamento'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='page_header_bg_color',
            field=colorfield.fields.ColorField(default='#003366', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#0d6efd', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='public_whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp Público de Contato'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='seo_description',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stat_clients',
            field=models.CharField(default='10.000+', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stat_destinations',
            field=models.CharField(default='500+', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stat_years',
            field=models.CharField(default='10+', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='televendas_benefits',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='televendas_page_subtitle',
            field=models.CharField(blank=True, default='Estamos prontos para o ajudar.', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='televendas_page_title',
            field=models.CharField(blank=True, default='Fale com nossa equipa de Televendas', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='televendas_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='top_bar_bg_color',
            field=colorfield.fields.ColorField(default='#F8F9FA', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='top_bar_text_color',
            field=colorfield.fields.ColorField(default='#6C757D', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='tracking_body_end_scripts',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='tracking_body_start_scripts',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='tracking_header_scripts',
            field=models.TextField(blank=True),
        ),
    ]
