# Generated by Django 5.2.5 on 2025-08-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('is_external', models.BooleanField(default=False, help_text='Marque se for um link para outro site.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Item do Menu Principal',
                'verbose_name_plural': 'Itens do Menu Principal',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Facebook, Instagram', max_length=100)),
                ('url', models.URLField(max_length=255)),
                ('icon_class', models.CharField(help_text='Ex: fa-brands fa-instagram.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopBarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='O texto que será exibido. Ex: Televendas 0800 883 6342', max_length=100)),
                ('url', models.CharField(blank=True, help_text='OPCIONAL. Deixe em branco se não for um link.', max_length=255)),
                ('icon_class', models.CharField(blank=True, help_text='Ex: fa-solid fa-phone.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Link do Menu Superior',
                'verbose_name_plural': 'Links do Menu Superior',
                'ordering': ['order'],
            },
        ),
    ]
