# Generated by Django 5.2.5 on 2025-08-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbarlink',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Ex: fa-solid fa-phone', max_length=100),
        ),
        migrations.AlterField(
            model_name='topbarlink',
            name='title',
            field=models.CharField(help_text='O texto que será exibido. Ex: Televendas 0800 883 6342', max_length=100),
        ),
        migrations.AlterField(
            model_name='topbarlink',
            name='url',
            field=models.CharField(blank=True, help_text='OPCIONAL. Deixe em branco para ser apenas texto. Para WhatsApp, use: https://wa.me/5511999999999', max_length=255),
        ),
    ]
