# Generated by Django 5.2.5 on 2025-08-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_topbarlink_icon_class_alter_topbarlink_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbarlink',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Ex: fa-solid fa-phone. Pegue os nomes do site Font Awesome.', max_length=100),
        ),
    ]
