# Generated by Django 5.2.5 on 2025-08-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_topbarlink_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Facebook, Instagram', max_length=100)),
                ('url', models.URLField(max_length=255)),
                ('icon_class', models.CharField(help_text='Ex: fa-brands fa-instagram. Pegue os nomes do site Font Awesome.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='topbarlink',
            name='url',
            field=models.CharField(blank=True, help_text='OPCIONAL. Deixe em branco se não for um link.', max_length=255),
        ),
    ]
