# Generated by Django 5.2.5 on 2025-08-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_socialmedialink_alter_topbarlink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='icon_class',
            field=models.CharField(help_text='Ex: fa-brands fa-instagram.', max_length=100),
        ),
        migrations.AlterField(
            model_name='topbarlink',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Ex: fa-solid fa-phone.', max_length=100),
        ),
    ]
