# Generated by Django 5.2.5 on 2025-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail do Inscrito')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
            ],
            options={
                'verbose_name': 'Inscrito na Newsletter',
                'verbose_name_plural': 'Inscritos na Newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
